version: 3.8

services:

  frontend:
    container_name: yale-access-frontend
    image: liamp1/yale-access-frontend:latest
    restart: unless-stopped

    ports: 5015:3000

    environment:
      - NUXT_PUBLIC_API_BASE_URL=http://<computer-ip>:5016

  backend:
    container_name: yale-access-backend
    image: liamp1/yale-access-backend:latest
    restart: unless-stopped

    ports: 5016:80

    environment:
      - LogLocation=/log/log.txt
      - CorsAllowedOrigins=http://<computer-ip>:5015
      - Devices__YaleLockNodeId=<node-id>
      - Codes__Home=<code-id>
      - Codes__GuestCodeRangeStart=<code-id>
      - GuestCodeRangeCount=<count>
      - ZWave__Url=http://<z-wave-ip>:<z-wave-port>
      - ZWave__SchemaVersion=<z-wave-schema>
      - Authentication__Password=<password>

    volumes:
      - ./log:/log