name: Build and Publish

on:
  push:
    branches:
    - main
    - feature/*  
    - fix/*
  pull_request:
    branches:
    - main

jobs:
  build-backend:
    name: Build Yale Access Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/backend

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

  publish-backend:
    name: Push Yale Access Backend Docker Image
    runs-on: ubuntu-latest
    needs: build-backend
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/yale-access-backend:latest
          context: ./packages/backend
          file: ./packages/backend/Dockerfile
          labels: |
            org.opencontainers.image.title=Yale Access Backend
            org.opencontainers.image.description=Backend for Yale Access

  build-frontend:
    name: Build Yale Access Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20.x

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn run build

  publish-frontend:
    name: Push Yale Access Frontend Docker Image
    runs-on: ubuntu-latest
    needs: build-frontend
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/yale-access-frontend:latest
          context: ./packages/frontend
          file: ./packages/frontend/Dockerfile
          labels: |
            org.opencontainers.image.title=Yale Access Frontend
            org.opencontainers.image.description=Frontend for Yale Access
